#!/usr/bin/env python3

# create a list containing multiple items
ip_list = [5060, "80", 55, "10.0.0.1", "10.20.30.1", "ssh"]

# display the first IP address
print(my_list[3])

# display the second IP address
print(my_list[4])
