#!/usr/bin/env python3
"""TLG NDE Python | Challenge
    print script containing user's name asking what day of the week it is"""

def main():

    #collect input asking the user's name
    name = input("Please enter your username")

    #collect input asking what day of the week it is
    day of the week = input("What day of the week is it?")
    
    ##print one statement containing name and day of the week
    print("Hello,"name,"Happy," day of the week"!")
    
main()    
